version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: udagram_postgres
    environment:
      POSTGRES_USER: full_stack_dev
      POSTGRES_PASSWORD: password123
    ports:
      - '5435:5432'
    env_file:
      - .env
    volumes:
      - 'postgres:/var/lib/postgresql/data'

volumes:
  postgres:
